#cloud-config
ssh_authorized_keys:
  - ${key_pairs}
coreos:
  units:
    - name: rsyslog-collector.service
      command: start
      runtime: true
      content: |
        [Unit]
        Description=Rsyslog Collector Server
        Requires=docker.socket
        After=docker.socket

        [Service]
        Environment=SERVICE=rsyslog-collector
        Environment=DOCKER_NAME=kam1kaze/rsyslog
        Environment=VERSION=latest
        Restart=on-failure
        RestartSec=30
        ExecStartPre=-/usr/bin/docker kill $${SERVICE}
        ExecStartPre=-/usr/bin/docker rm $${SERVICE}
        ExecStartPre=/usr/bin/docker pull $${DOCKER_NAME}:$${VERSION}
        ExecStartPre=/usr/bin/install -d -g 0 -o 0 -m 700 /data/logs
        ExecStart=/usr/bin/docker run --name $${SERVICE} \
                                      -v /data/logs:/var/log \
                                      --env ROLE=collector \
                                      --env RSYSLOG_FORWARD_IP=${rsyslog_relay_ip} \
                                      --env RSYSLOG_FORWARD_PROTOCOL=udp \
                                      $${DOCKER_NAME}:$${VERSION}
    - name: nginx.service
      command: start
      runtime: true
      content: |
        [Unit]
        Description=Nginx Test Daemon
        Requires=docker.socket rsyslog-collector.service
        After=docker.socket rsyslog-collector.service

        [Service]
        Environment=SERVICE=nginx
        Environment=DOCKER_NAME=nginx
        Environment=VERSION=alpine
        Restart=on-failure
        RestartSec=30
        ExecStartPre=-/usr/bin/docker kill $${SERVICE}
        ExecStartPre=-/usr/bin/docker rm $${SERVICE}
        ExecStartPre=/usr/bin/docker pull $${DOCKER_NAME}:$${VERSION}
        ExecStart=/usr/bin/docker run --name $${SERVICE} \
                                      --volumes-from rsyslog-collector \
                                      -p 80:80 \
                                      $${DOCKER_NAME}:$${VERSION} \
                                      sh -xc 'mkdir -p /var/log/nginx/ && exec nginx -g "daemon off;"'
